##  Project Description

This capstone project will focus on analyzing sales data for EmporiUm a growing student book store that sells book,technology products,art supplies, and other merchandise through both physical stores and online sales channels.The purpose of the project is to help management beter understand sales performance across the 2 territories I was assigned,to identify trends that can support business decisions.

# Analysis on territories Maine & Maryland

For this analysis the sales territories being examined are Maine and Maryland, that are located in the NorthEast region.
This project will compare these two territories by evaluating sales performance,product trends,customer activity and related manager concerns

Below this line will be the data for this projects analysis.
Each file is open using read_csv pandas function with .info() attached to it for quick summary of the data
and important information referencing to that table.

In [5]:
import pandas as pd

In [6]:
products = pd.read_csv("Products.csv")
Product_cat = pd.read_csv("ProductCategories.csv")
Store_D = pd.read_csv("StoreDetail.csv")
Store_S = pd.read_csv("StoreSales.csv")
Customer = pd.read_csv("customer_list.csv")

In [7]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    str
 1   Product        669 non-null    str
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    str
dtypes: int64(1), str(3)
memory usage: 21.0 KB

In [8]:
Product_cat.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     str
 2   SubcategoryID  52 non-null     str
 3   Subcategory    52 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.8 KB

In [9]:
Store_D.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    str
 1   State              111 non-null    str
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    str
 4   Region             111 non-null    str
 5   Region Director    111 non-null    str
dtypes: int64(1), str(5)
memory usage: 5.3 KB

In [10]:
Store_S.info()

<class 'pandas.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  str
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  str
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 12.8 MB

In [11]:
Customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    str
dtypes: str(1)
memory usage: 4.2 KB

# Customer data organization fix

In [12]:
Customer = pd.read_csv("customer_list.csv",sep="|")
#Load the customer file using pipe seperator,it's not seperated in commas.

In [13]:
Customer.to_csv("customer_list_limpio.csv",index=False)
#Exports the data frame back out as a standard comm-seperated CSV,just using the pipe instead

In [14]:
Customer = pd.read_csv("customer_list_limpio.csv")

In [15]:
Customer.head()

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

## --- Core Marketing Analysis ---

# Question 1.)
## Who are the territory managers for the sales territories assigned? What are the store IDs and cities for the stores in each assigned sales territory?

In [16]:
Store_D.head()
#helps view columns im working with to get information

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [17]:
territories = Store_D[
    Store_D["State"].isin(["Maine","Maryland"])]

territories[["State",
             "Territory Manager",
             "Store ID",
             "Store Location"]]

       State  Territory Manager  Store ID       Store Location
37     Maine  Erbayne Middleton       818               Bangor
38     Maine  Erbayne Middleton       819           Bar Harbor
39     Maine  Erbayne Middleton       820        Kennebunkport
40     Maine  Erbayne Middleton       821             Lewiston
41     Maine  Erbayne Middleton       822                Orono
42     Maine  Erbayne Middleton       823       South Portland
43  Maryland       Shruti Reddy       731            Annapolis
44  Maryland       Shruti Reddy       732           Back River
45  Maryland       Shruti Reddy       733            Baltimore
46  Maryland       Shruti Reddy       734           Germantown
47  Maryland       Shruti Reddy       735               Howard
48  Maryland       Shruti Reddy       736        North Harford
49  Maryland       Shruti Reddy       737            Parkville
50  Maryland       Shruti Reddy       738  Queen Anne's County
51  Maryland       Shruti Reddy       739              Ridgely

# Analysis for question 1:

Now that we removed  the territories that are irrelavent  from the list we can now only see the  assigned territories we were introduced to, we can see
below the managers for maine and Maryland.
Maryland: Shruti Reddy 
Maine: Erbayne Middleton

# Question 2.)
# What is monthly total revenue for in-store sales in each of the two sales territories, over the full period covered by the data?

In [18]:
Store_S.head()
# view columns to be able to understand question

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [19]:
Store_D.head()
# view columns to be able to understand question

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

# Monthly revenues for Maine and Maryland

In [68]:
# change transaction date to date time 
# extract month

Store_S["Transaction Date"] = pd.to_datetime(Store_S["Transaction Date"])

In [69]:
# create column for month--
Store_S["Month"] = Store_S["Transaction Date"].dt.to_period("M")

In [83]:
#Join sales and store detail tables

sales_merged = Store_S.merge(
    Store_D,
    on = "Store ID",
    how="left")

In [95]:
sales_merged.head()
# show tables merged

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Month,Store Location,State,Territory Manager,Region,Region Director
0,2022-01-01,702,NaN,105349-M,8.00,2022-01,Berthoud,Colorado,Jim Heck,West,Cassie Chambers
1,2022-01-01,704,NaN,105350-T,144.00,2022-01,Castle Rock,Colorado,Jim Heck,West,Cassie Chambers
2,2022-01-01,705,NaN,105351-M,44.00,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers
3,2022-01-01,705,NaN,105352-M,47.61,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers
4,2022-01-01,705,NaN,105353-A,20.36,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers

In [86]:
# show only Maine and maryland
# This will filter the sales_merged to only show maine and Maryland

sales_filtered = sales_merged[
    sales_merged["State"].isin(["Maine","Maryland"])]

In [107]:
# Calculate monthly revenue totals
monthly_revenue = sales_filtered.groupby(
    ["State","Month"])["Sale Amount"].sum().reset_index()

In [108]:
monthly_revenue = monthly_revenue.sort_values(by=["State","Month"])

In [109]:
monthly_revenue.style.hide(axis="index")

# Total Revenue over full data period for Maine and Maryland

In [92]:
total_revenue = sales_filtered.groupby("State")["Sale Amount"].sum().reset_index()

In [93]:
total_revenue = total_revenue.sort_values(by="Sale Amount",ascending=False)
# Sorting highest revenue state first

In [29]:
total_revenue

      State  Sale Amount
1  Maryland  11451615.09
0     Maine   1877249.75

# Question 3.) How would you rank the sales performance of each store in each sales territory? Which are the top-performing stores?

In [81]:
# Group total sales by state,store id and store location
store_performance = sales_filtered.groupby(["State","Store ID","Store Location"])["Sale Amount"].sum().reset_index()
 
# Sort stores from highest to lowest sales
store_performance = store_performance.sort_values(by="Sale Amount",ascending=False)

In [82]:
store_performance.style.hide(axis="index")

In [111]:
sales_filtered[sales_filtered["Store ID"] == 736]

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Month,Store Location,State,Territory Manager,Region,Region Director
36,2022-01-01,736,NaN,105310-IT,71.74,2022-01,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
37,2022-01-01,736,NaN,105326-IT,1717.70,2022-01,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
38,2022-01-01,736,NaN,105311-IT,69.90,2022-01,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
39,2022-01-01,736,NaN,105282-IT,237.28,2022-01,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
40,2022-01-01,736,NaN,105303-IT,76.86,2022-01,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
...,...,...,...,...,...,...,...,...,...,...,...
334939,2025-12-31,736,467.0,105341-IT,1763.70,2025-12,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
334940,2025-12-31,736,NaN,105319-IT,30.16,2025-12,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
334941,2025-12-31,736,NaN,105261-IT,622.32,2025-12,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
334942,2025-12-31,736,NaN,105287-IT,126.18,2025-12,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis
334943,2025-12-31,736,NaN,105248-IT,883.48,2025-12,North Harford,Maryland,Shruti Reddy,Northeast,Michael Jarvis

In [35]:
sales_filtered[sales_filtered["Store ID"] == 736].shape

(69530, 11)

# Question 4.)

# Comparing the customer ID from the customer list data with the rewards ID from the sales data, who were the top customers in each sales territory?

In [38]:
# merge customer info with sales data
customer_sales = sales_filtered.merge(
    Customer,
    left_on="RewardsID",
    right_on="cust_id",
    how="left")

In [40]:
#Group Total sales by state and customer name
top_customers = customer_sales.groupby(
    ["State","name"])["Sale Amount"].sum().reset_index()

In [42]:
# Sort highest spending customers first
top_customers=top_customers.sort_values(by="Sale Amount",ascending=False)

In [45]:
# Results
top_customers.style.hide(axis="index")

Below are the top customers per territory

# Maine

In [47]:

top_customers[top_customers["State"] == "Maine"].head(1).style.hide(axis="index")

# Maryland

In [48]:
top_customers[top_customers["State"] == "Maryland"].head(1).style.hide(axis="index")

# Question 5.)

What is the number of transactions per month by product category in each assigned territory?
What is total sales revenue per month by category? What might this tell you about the most
popular products, and where could there be opportunity for growth?

In [51]:
# Merging products table with category table
product_data = products.merge(
    Product_cat,
    on=["CategoryID","SubcategoryID"],how="left")

In [52]:
# Merge sales data with product and category information
sales_products=sales_filtered.merge(
    product_data,
    on="Prod Num",
    how="left")

In [53]:
# Count transactions by state,month, and category 
monthly_transactions = sales_products.groupby(["State","Month","Category"]).size().reset_index(name="Transaction Count")

In [56]:
# sort results
month_transactions = monthly_transactions.sort_values(by=["State","Month","Transaction Count"],ascending=[True,True,False])

In [57]:
# Show results without index 
monthly_transactions.style.hide(axis="index")

# Question 5.) Part 2.

 What is the total sale revenue per month by category?

In [65]:
# Calculate revenue totals by state,month, and category
monthly_category_revenue = sales_products.groupby(["State","Month","Category"])["Sale Amount"].sum().reset_index()

In [66]:
# sort results
monthly_category_revenue = monthly_category_revenue.sort_values(by=["State","Month","Sale Amount"],ascending=[True,True,False])

In [67]:
monthly_category_revenue.style.hide(axis="index")

# Question 6.)

What is your recommendation for where to focus marketing attention in the next quarter?